version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: transactions-api
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/:/docker-entrypoint-initdb.d/:ro
    networks:
      - postgres-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/transactions-api
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - '8080:8080'
    networks:
      - postgres-network

networks:
  postgres-network:

volumes:
  postgres-data:
