spring:
  application.name: transaction-api
  datasource:
    url: jdbc:postgresql://localhost:5432/transactions-api
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect